# This file is automatically generated from cpp-doctor.toml - DO NOT EDIT
#
# Unlike cmkr, cpp-doctor does NOT build itself from source. It is shipped as a
# binary/installer; this script only locates the `cpp-doctor` executable on PATH
# (or via -DCPPDOCTOR_EXECUTABLE=...) and regenerates CMakeLists.txt when the
# manifest changes.

include_guard()

# Override these from the command line for development/debugging purposes
set(CPPDOCTOR_EXECUTABLE "" CACHE FILEPATH "cpp-doctor executable")
set(CPPDOCTOR_SKIP_GEN OFF CACHE BOOL "skip automatic cpp-doctor generation")
mark_as_advanced(CPPDOCTOR_EXECUTABLE CPPDOCTOR_SKIP_GEN)

# Disable generation in CI or when explicitly skipped: use the committed CMakeLists.txt
if(DEFINED ENV{CI} OR CPPDOCTOR_SKIP_GEN)
    message(STATUS "[cpp-doctor] Skipping automatic generation")
    macro(cpp_doctor)
    endmacro()
    return()
endif()

# Disable cpp-doctor if no cpp-doctor.toml is found
if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/cpp-doctor.toml")
    message(AUTHOR_WARNING "[cpp-doctor] Not found: ${CMAKE_CURRENT_SOURCE_DIR}/cpp-doctor.toml")
    macro(cpp_doctor)
    endmacro()
    return()
endif()

# Locate the cpp-doctor binary (it is installed, never built from source here)
if(NOT CPPDOCTOR_EXECUTABLE)
    find_program(CPPDOCTOR_EXECUTABLE cpp-doctor)
endif()

# If the binary is absent, warn and continue using the committed CMakeLists.txt
if(NOT CPPDOCTOR_EXECUTABLE)
    message(AUTHOR_WARNING
        "[cpp-doctor] Could not find the 'cpp-doctor' executable on PATH. "
        "Using the committed CMakeLists.txt without regeneration. "
        "Install cpp-doctor or set -DCPPDOCTOR_EXECUTABLE=... to enable automatic generation."
    )
    macro(cpp_doctor)
    endmacro()
    return()
endif()

# Helper to run a process and fail loudly
function(cpp_doctor_exec)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE CPPDOCTOR_EXEC_RESULT)
    if(NOT CPPDOCTOR_EXEC_RESULT EQUAL 0)
        message(FATAL_ERROR "cpp_doctor_exec(${ARGV}) failed (exit code ${CPPDOCTOR_EXEC_RESULT})")
    endif()
endfunction()

# The macro that wires up automatic regeneration
macro(cpp_doctor)
    # Mark whether this is the root project (mirrors the generated CMakeLists.txt)
    set(CPPDOCTOR_ROOT_PROJECT OFF)
    if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
        set(CPPDOCTOR_ROOT_PROJECT ON)

        # Create a configure-time dependency on cpp-doctor.toml to improve IDE support
        configure_file(cpp-doctor.toml cpp-doctor.toml COPYONLY)
    endif()

    # File-based include guard so we only regenerate once per configure
    get_source_file_property(CPPDOCTOR_INCLUDE_GUARD "${CMAKE_CURRENT_LIST_FILE}" CPPDOCTOR_INCLUDE_GUARD)
    if(NOT CPPDOCTOR_INCLUDE_GUARD)
        set_source_files_properties("${CMAKE_CURRENT_LIST_FILE}" PROPERTIES CPPDOCTOR_INCLUDE_GUARD TRUE)

        set(CPPDOCTOR_TOML "${CMAKE_CURRENT_SOURCE_DIR}/cpp-doctor.toml")
        set(CPPDOCTOR_LIST "${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.txt")

        # Regenerate only when the manifest is newer than the generated CMakeLists.txt
        if("${CPPDOCTOR_TOML}" IS_NEWER_THAN "${CPPDOCTOR_LIST}")
            message(STATUS "[cpp-doctor] cpp-doctor.toml changed, regenerating CMakeLists.txt")
            cpp_doctor_exec("${CPPDOCTOR_EXECUTABLE}" gen
                WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
            )

            # Re-include the freshly generated CMakeLists.txt via a temporary copy
            # (you cannot include() the file currently being processed).
            set(CPPDOCTOR_TEMP_FILE "${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.cpp-doctor.txt")
            configure_file(CMakeLists.txt "${CPPDOCTOR_TEMP_FILE}" COPYONLY)
            include("${CPPDOCTOR_TEMP_FILE}")
            file(REMOVE "${CPPDOCTOR_TEMP_FILE}")

            # Do not continue executing the stale CMakeLists.txt
            return()
        endif()
    endif()
endmacro()
