//! Expectation tracking — a lightweight, self-contained regression guard.
//!
//! Modeled on the *idea* behind Servo's `*.ini` WPT metadata and Blitz's
//! expectation files (a committed record of how each test is expected to behave,
//! so CI fails when reality regresses) — but kept deliberately tiny: no INI
//! parser, no per-subtest granularity, no external crate. One plain-text file per
//! suite, one line per test.
//!
//! ## File format (`expectations/<suite>.txt`)
//!
//! ```text
//! # canopy-wpt expectations baseline
//! # suite: css-grid
//! # generated by: canopy-wpt --write-baseline
//! # counts: PASS=12 FAIL=3 SKIP=40 CRASH=0  (total 55)
//! #
//! # One line per test: "<STATUS>\t<NAME>". STATUS is the EXPECTED disposition.
//! # `--check` re-runs the suite and FAILS (non-zero exit) if any test that was
//! # PASS here is no longer PASS — i.e. a regression. New tests (not in the
//! # baseline) and improvements (FAIL/SKIP -> PASS) never fail the check; they are
//! # reported so the baseline can be refreshed with `--write-baseline`.
//! PASS  css/css-grid/grid-support-001.html
//! FAIL  css/css-grid/grid-template-areas-001.html
//! SKIP  css/css-grid/grid-writing-mode-001.html
//! ```
//!
//! The status vocabulary matches the runner's [`crate::Outcome`] tags exactly:
//! `PASS`, `FAIL`, `SKIP`, `CRASH`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::{fs, io};

/// The expected disposition of a single test, mirroring the runner's outcome
/// tags. `Crash` is tracked as its own status (not folded into `Fail`) so that a
/// PASS/FAIL test turning into a panic is caught as a regression too.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Status {
    Pass,
    Fail,
    Skip,
    Crash,
}

impl Status {
    /// The four-letter token used in the baseline file and reports.
    pub fn token(self) -> &'static str {
        match self {
            Status::Pass => "PASS",
            Status::Fail => "FAIL",
            Status::Skip => "SKIP",
            Status::Crash => "CRASH",
        }
    }

    fn parse(s: &str) -> Option<Status> {
        match s {
            "PASS" => Some(Status::Pass),
            "FAIL" => Some(Status::Fail),
            "SKIP" => Some(Status::Skip),
            "CRASH" => Some(Status::Crash),
            _ => None,
        }
    }
}

/// A baseline: the expected status of every test, keyed by test name. Sorted
/// (BTreeMap) so the serialized file is deterministic and diff-friendly.
pub struct Baseline {
    pub suite: String,
    pub statuses: BTreeMap<String, Status>,
}

impl Baseline {
    /// Build a baseline from `(name, status)` pairs (the current run's results).
    pub fn from_results(suite: &str, results: impl IntoIterator<Item = (String, Status)>) -> Self {
        Baseline {
            suite: suite.to_string(),
            statuses: results.into_iter().collect(),
        }
    }

    /// Parse a baseline file. Blank lines and `#` comments are ignored; every
    /// other line must be `STATUS<TAB or spaces>NAME`.
    pub fn load(path: &Path) -> io::Result<Baseline> {
        let text = fs::read_to_string(path)?;
        let mut suite = String::new();
        let mut statuses = BTreeMap::new();
        for line in text.lines() {
            let line = line.trim_end();
            if let Some(rest) = line.strip_prefix("# suite:") {
                suite = rest.trim().to_string();
                continue;
            }
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            // Split on the first run of whitespace: "STATUS<ws>NAME".
            let mut parts = line.splitn(2, char::is_whitespace);
            let Some(tok) = parts.next() else { continue };
            let Some(name) = parts.next() else { continue };
            let name = name.trim();
            if let Some(status) = Status::parse(tok) {
                statuses.insert(name.to_string(), status);
            }
        }
        Ok(Baseline { suite, statuses })
    }

    /// Serialize to the on-disk text format (deterministic, sorted).
    pub fn serialize(&self) -> String {
        let (mut pass, mut fail, mut skip, mut crash) = (0u32, 0u32, 0u32, 0u32);
        for s in self.statuses.values() {
            match s {
                Status::Pass => pass += 1,
                Status::Fail => fail += 1,
                Status::Skip => skip += 1,
                Status::Crash => crash += 1,
            }
        }
        let total = self.statuses.len();

        let mut out = String::new();
        let _ = writeln!(out, "# canopy-wpt expectations baseline");
        let _ = writeln!(out, "# suite: {}", self.suite);
        let _ = writeln!(out, "# generated by: canopy-wpt --write-baseline");
        let _ = writeln!(
            out,
            "# counts: PASS={pass} FAIL={fail} SKIP={skip} CRASH={crash}  (total {total})"
        );
        let _ = writeln!(out, "#");
        let _ = writeln!(
            out,
            "# One line per test: \"<STATUS>\\t<NAME>\". STATUS is the EXPECTED disposition."
        );
        let _ = writeln!(
            out,
            "# `--check` FAILS (non-zero exit) if any PASS test here is no longer PASS."
        );
        for (name, status) in &self.statuses {
            let _ = writeln!(out, "{}\t{}", status.token(), name);
        }
        out
    }

    /// Write the baseline to disk (creating parent dirs as needed).
    pub fn write(&self, path: &Path) -> io::Result<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, self.serialize())
    }
}

/// One test whose status got worse relative to the baseline.
pub struct Regression {
    pub name: String,
    pub was: Status,
    pub now: Status,
}

/// One test that improved or is newly passing relative to the baseline.
pub struct Improvement {
    pub name: String,
    /// `None` for a brand-new test absent from the baseline.
    pub was: Option<Status>,
    pub now: Status,
}

/// The full diff of a current run against a committed baseline.
pub struct CheckReport {
    /// Tests that REGRESSED: were `PASS` in the baseline, no longer `PASS`. These
    /// are what fail CI.
    pub regressions: Vec<Regression>,
    /// Tests that IMPROVED to `PASS` (were non-`PASS` or brand new). Informational.
    pub improvements: Vec<Improvement>,
    /// Tests present in the baseline but absent from this run (e.g. suite shrank).
    pub missing: Vec<String>,
}

impl CheckReport {
    /// `true` iff there is at least one regression (PASS -> not-PASS).
    pub fn has_regressions(&self) -> bool {
        !self.regressions.is_empty()
    }
}

/// Compare `current` run results against `baseline`. A REGRESSION is any test the
/// baseline expected to `PASS` that is no longer `PASS`. Improvements and missing
/// tests are reported but never fail the check (so the guard is strictly a
/// ratchet: it only resists getting worse).
pub fn check(baseline: &Baseline, current: &[(String, Status)]) -> CheckReport {
    let current_map: BTreeMap<&str, Status> =
        current.iter().map(|(n, s)| (n.as_str(), *s)).collect();

    let mut regressions = Vec::new();
    let mut improvements = Vec::new();
    let mut missing = Vec::new();

    for (name, &expected) in &baseline.statuses {
        match current_map.get(name.as_str()) {
            Some(&now) => {
                if expected == Status::Pass && now != Status::Pass {
                    regressions.push(Regression {
                        name: name.clone(),
                        was: expected,
                        now,
                    });
                } else if expected != Status::Pass && now == Status::Pass {
                    improvements.push(Improvement {
                        name: name.clone(),
                        was: Some(expected),
                        now,
                    });
                }
            }
            None => missing.push(name.clone()),
        }
    }

    // Brand-new passing tests (in the run, not in the baseline) are improvements.
    for (name, &now) in &current_map {
        if !baseline.statuses.contains_key(*name) && now == Status::Pass {
            improvements.push(Improvement {
                name: name.to_string(),
                was: None,
                now,
            });
        }
    }

    regressions.sort_by(|a, b| a.name.cmp(&b.name));
    improvements.sort_by(|a, b| a.name.cmp(&b.name));
    missing.sort();

    CheckReport {
        regressions,
        improvements,
        missing,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base(pairs: &[(&str, Status)]) -> Baseline {
        Baseline::from_results("css-test", pairs.iter().map(|(n, s)| (n.to_string(), *s)))
    }

    #[test]
    fn roundtrip_serialize_parse() {
        let b = base(&[
            ("a.html", Status::Pass),
            ("b.html", Status::Fail),
            ("c.html", Status::Skip),
            ("d.html", Status::Crash),
        ]);
        let text = b.serialize();
        let dir = std::env::temp_dir().join(format!("canopy-wpt-test-{}", std::process::id()));
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("roundtrip.txt");
        fs::write(&path, &text).unwrap();
        let loaded = Baseline::load(&path).unwrap();
        assert_eq!(loaded.suite, "css-test");
        assert_eq!(loaded.statuses.len(), 4);
        assert!(matches!(loaded.statuses.get("a.html"), Some(Status::Pass)));
        assert!(matches!(loaded.statuses.get("d.html"), Some(Status::Crash)));
    }

    #[test]
    fn detects_pass_to_fail_regression() {
        let b = base(&[("a.html", Status::Pass), ("b.html", Status::Fail)]);
        let current = vec![
            ("a.html".to_string(), Status::Fail), // regressed
            ("b.html".to_string(), Status::Fail), // unchanged
        ];
        let report = check(&b, &current);
        assert!(report.has_regressions());
        assert_eq!(report.regressions.len(), 1);
        assert_eq!(report.regressions[0].name, "a.html");
    }

    #[test]
    fn pass_to_crash_is_a_regression() {
        let b = base(&[("a.html", Status::Pass)]);
        let current = vec![("a.html".to_string(), Status::Crash)];
        let report = check(&b, &current);
        assert!(report.has_regressions());
    }

    #[test]
    fn improvement_does_not_fail() {
        let b = base(&[("a.html", Status::Fail), ("b.html", Status::Skip)]);
        let current = vec![
            ("a.html".to_string(), Status::Pass),   // improved
            ("b.html".to_string(), Status::Skip),   // unchanged
            ("new.html".to_string(), Status::Pass), // brand new pass
        ];
        let report = check(&b, &current);
        assert!(!report.has_regressions());
        assert_eq!(report.improvements.len(), 2);
    }

    #[test]
    fn missing_test_is_reported_not_a_regression() {
        let b = base(&[("a.html", Status::Pass), ("gone.html", Status::Pass)]);
        let current = vec![("a.html".to_string(), Status::Pass)];
        let report = check(&b, &current);
        assert!(!report.has_regressions());
        assert_eq!(report.missing, vec!["gone.html".to_string()]);
    }
}
